# -*- coding: utf-8 -*-
"""list_Explanation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMR2yLR-tWaG2fUaolhWyC83zZ1TAnm5
"""

i=5

type(i)

i=5.0
type(i)



"""list"""

l=[]
l

type(l)

l.append(10)

l

l.append(20)
l.append(30)
l.append(40)
l.append(50)
l

l.append(60)

l.append(70,80,90)

l

l.append(10)

l

len(l)

l1

l1=l.copy()

l1

l1.append(2.3)
l1.append('nit')
l1.append(1+2j)
l1.append([1,2,3])

print(l)
print(l1)

print(len(l))
print(len(l1))

l==l1

l2=l.copy()

l==l2

print(l)
print(l1)
print(l2)

l[:]

l[0]

l[0]=100

l

l[-1]=200

l

l[3:]

l[10]

l[10:]

l[:10]

l[-1]

l2.clear()

l2

del l2

l2

l1

len(l)

[l1[0:12:5]]

l1[0:11:3]

l1.index('nit')

