# -*- coding: utf-8 -*-
"""22_list_Explanation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMR2yLR-tWaG2fUaolhWyC83zZ1TAnm5
"""

i=5

type(i)

i=5.0
type(i)



"""list"""

l=[]
l

type(l)

l.append(10)

l

l.append(20)
l.append(30)
l.append(40)
l.append(50)
l

l.append(60)

l.append(70,80,90)

l

l.append(10)

l

len(l)

l1

l1=l.copy()

l1

l1.append(2.3)
l1.append('nit')
l1.append(1+2j)
l1.append([1,2,3])

print(l)
print(l1)

print(len(l))
print(len(l1))

l==l1

l2=l.copy()

l==l2

print(l)
print(l1)
print(l2)

l[:]

l[0]

l[0]=100

l

l[-1]=200

l

l[3:]

l[10]

l[10:]

l[:10]

l[-1]

l2.clear()

l2

del l2

l2

l1

len(l)

[l1[0:12:5]]

l1[0:11:3]

l1.index('nit')

l1.count(100)

l1

l1=[10, 20, 30, 40, 50, 60, 10, 2.3, 'nit', (1+2j), [1, 2, 3]]

l1

l1.count(100)

l1.count(10)

l1.remove([1,2,3])

l1.remove(10)

l1

l

l=[100,20,30,40,50,60,200]

l

l.insert(2,25)

l

l.pop()

l1.pop()

l

l.pop(20)

l.pop(0)

l

l2

l1

l1

len(l)

len(l1)

l1=[[20, 30, 40, 50, 60,10, 2.3, 'nit']]

l1

l3=l1.copy()

l3

l1.extend(l3)

l1

l1=[[20, 30, 40, 50, 60,10, 2.3, 'nit']]

l3

l9=[3,7,10,1,1,100,95]

l

l=[100,20,30,40,50,60,200]

l1=[10,202,30,40,50,60,10,2.3,'nit',(1+2j),[1,2,3]]

l

l1

l.count(100)

l1.remove([1,2,3])

l1

l.remove(10)

l1.remove(10)

l1

l.append(25) # this will add the value in last

l

l.insert(2,25) # this means 2nd index inser the value 25

l

l1

l1.pop() # this means remove the last element and return the value

l1

l

l.remove(100)

l

l.pop(20) # this will throw ans error because we pass the value inside the pop function this will indicate the index number in the list

l

l.pop(0) # this will remove first index number in list

l

len(l)

l.pop()

len(l)

len(l1)

l3=l1.copy()

l3==l1

l1.extend(l3)

l1

l4=[4,5,6]

l7=[1,2]

l7

l7.extend(l4)

l7

l10=[1,2,3]

l10

l10.reverse()

l10

l9=[3,7,10,1,100,95]

l9

l9.sort()

l9

l9.sort(reverse=True)

l9

