# -*- coding: utf-8 -*-
"""SET_Classwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_7h0pSa4CC7Lh2d4hiaxU56WDm0jI4D
"""



"""# 24th_set_class

**set**
"""

s={}
s

type(s)

s1=set()
type(s1)

s1

s1.add(10)

s1

s1.add(20)
s1.add('nit')

s1.add(True)

s1.add(1+2j)

s1.add(3.2)

s1

s2= set()
s2

s2.add(100)
s2.add(10)
s2.add(200)
s2.add(9)

s3=set()

s3.add('z')
s3.add('a')
s3.add('m')
s3.add('n')

s3

del s3

s3=set()

s3.add('z')
s3.add('a')
s3.add('m')
s3.add('n')

print(s1)
print(s2)
print(s3)

print(len(s3))

s3

s3[0]

s3[:]

s4=s3.copy()

s4

s3

s3==s4

s4.clear()

del s4

s4

s4=s2.copy()

s4

s4.pop()

s4.pop()

s1.pop(0)

s1

s1.remove((1+2j))

for i in s4:
  print (i)

for i in enumerate(s4):
    print(i)

"""**Set operation **"""

## Set operation

A={1,2,3,4,5}
B={4,5,6,7,8}
C={8,9,10}

A|B # UNION

B.union(C)

A.union(B,C)

C|B|A

"""Update"""

C={8,9,10}

C.update(B)

C

A

b

B

C

A&B

B.intersection(C)

A&B&C



"""Difference"""

print(A)

print(A)
print(B)
print(C)

A-B

B - C

C -A

C.difference(A)